[project]
name = "funsearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ipython>=8.12.3",
    "numpy>=1.24.4",
]

[dependency-groups]
dev = [
    "ruff>=0.14.6",
]
